name: CI

on:
  pull_request:
  push:

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Nix install
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix-build

      - name: Test
        run: ./result/bin/ormolu --version
